window.WORD_BANK = [
  { id: "1", word: "hesitate", phonetic: "/ˈhezɪteɪt/", meaning: "v. 犹豫，踌躇", weight: 0, errorCount: 0 },
  { id: "2", word: "allocate", phonetic: "/ˈæləkeɪt/", meaning: "v. 分配", weight: 0, errorCount: 0 },
  { id: "3", word: "interpret", phonetic: "/ɪnˈtɜːrprɪt/", meaning: "v. 解释", weight: 0, errorCount: 0 },
  { id: "4", word: "constrain", phonetic: "/kənˈstreɪn/", meaning: "v. 限制", weight: 0, errorCount: 0 },
  { id: "5", word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", meaning: "v. 波动", weight: 0, errorCount: 0 },
  { id: "6", word: "deteriorate", phonetic: "/dɪˈtɪriəreɪt/", meaning: "v. 恶化", weight: 0, errorCount: 0 },
  { id: "7", word: "plausible", phonetic: "/ˈplɔːzəbl/", meaning: "adj. 貌似合理的", weight: 0, errorCount: 0 },
  { id: "8", word: "coherent", phonetic: "/koʊˈhɪrənt/", meaning: "adj. 连贯的", weight: 0, errorCount: 0 },
  { id: "9", word: "subtle", phonetic: "/ˈsʌtl/", meaning: "adj. 微妙的", weight: 0, errorCount: 0 },
  { id: "10", word: "inevitable", phonetic: "/ɪnˈevɪtəbl/", meaning: "adj. 不可避免的", weight: 0, errorCount: 0 },
  { id: "11", word: "compile", phonetic: "/kəmˈpaɪl/", meaning: "v. 汇编，编纂", weight: 0, errorCount: 0 },
  { id: "12", word: "retain", phonetic: "/rɪˈteɪn/", meaning: "v. 保持，保留", weight: 0, errorCount: 0 },
  { id: "13", word: "adjacent", phonetic: "/əˈdʒeɪsnt/", meaning: "adj. 邻近的", weight: 0, errorCount: 0 },
  { id: "14", word: "notion", phonetic: "/ˈnoʊʃn/", meaning: "n. 概念，看法", weight: 0, errorCount: 0 },
  { id: "15", word: "comprise", phonetic: "/kəmˈpraɪz/", meaning: "v. 包含", weight: 0, errorCount: 0 },
  { id: "16", word: "rigorous", phonetic: "/ˈrɪɡərəs/", meaning: "adj. 严谨的", weight: 0, errorCount: 0 },
  { id: "17", word: "transient", phonetic: "/ˈtrænʒnt/", meaning: "adj. 短暂的", weight: 0, errorCount: 0 },
  { id: "18", word: "intrinsic", phonetic: "/ɪnˈtrɪnsɪk/", meaning: "adj. 内在的", weight: 0, errorCount: 0 },
  { id: "19", word: "facilitate", phonetic: "/fəˈsɪlɪteɪt/", meaning: "v. 促进", weight: 0, errorCount: 0 },
  { id: "20", word: "derive", phonetic: "/dɪˈraɪv/", meaning: "v. 得出，来源于", weight: 0, errorCount: 0 },
  { id: "21", word: "profound", phonetic: "/prəˈfaʊnd/", meaning: "adj. 深刻的", weight: 0, errorCount: 0 },
  { id: "22", word: "deviate", phonetic: "/ˈdiːvieɪt/", meaning: "v. 偏离", weight: 0, errorCount: 0 },
  { id: "23", word: "convention", phonetic: "/kənˈvenʃn/", meaning: "n. 传统，惯例", weight: 0, errorCount: 0 },
  { id: "24", word: "meticulous", phonetic: "/məˈtɪkjələs/", meaning: "adj. 一丝不苟的", weight: 0, errorCount: 0 },
  { id: "25", word: "intact", phonetic: "/ɪnˈtækt/", meaning: "adj. 完好无损的", weight: 0, errorCount: 0 },
  { id: "26", word: "attribute", phonetic: "/əˈtrɪbjuːt/", meaning: "v. 归因于", weight: 0, errorCount: 0 },
  { id: "27", word: "perspective", phonetic: "/pərˈspektɪv/", meaning: "n. 视角", weight: 0, errorCount: 0 },
  { id: "28", word: "subsequent", phonetic: "/ˈsʌbsɪkwənt/", meaning: "adj. 随后的", weight: 0, errorCount: 0 },
  { id: "29", word: "empirical", phonetic: "/ɪmˈpɪrɪkl/", meaning: "adj. 经验主义的", weight: 0, errorCount: 0 },
  { id: "30", word: "sustain", phonetic: "/səˈsteɪn/", meaning: "v. 维持", weight: 0, errorCount: 0 }
];

